# Generated by Django 5.0 on 2023-12-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetariumdome",
            name="seats_in_row",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
