# Generated by Django 5.0 on 2023-12-12 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_planetariumdome_seats_in_row"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("show_session", "row", "seat")},
        ),
    ]
