# Generated by Django 5.0 on 2023-12-12 10:38

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0004_alter_reservation_options_alter_ticket_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ("title",)},
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.movie_image_file_path
            ),
        ),
    ]
